export const GET_INTERVENTIONS = "GET_INTERVENTIONS";
export const GET_INTERVENTIONS_SUCCESS = "GET_INTERVENTIONS_SUCCESS";
export const GET_INTERVENTIONS_FAIL = "GET_INTERVENTIONS_FAIL";
export const GET_INTERVENTION = "GET_INTERVENTION";
export const GET_INTERVENTION_SUCCESS = "GET_INTERVENTION_SUCCESS";
export const GET_INTERVENTION_FAIL = "GET_INTERVENTION_FAIL";
export const CREATE_INTERVENTION = "CREATE_INTERVENTION";
